obj-$(CONFIG_BB_XYLON) += xylonbb.o
xylonbb-objs := ../core/xylonbb.o ../core/xylonbb-ioctl.o \
	../core/xylonbb-pixclk.o
xylonbb-$(CONFIG_BB_XYLON_LOGICLK_PIXCLK) += ../core/logiclk.o
xylonbb-$(CONFIG_BB_XYLON_PLATFORM) += xylonbb-platform.o
